#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""
Analyze PyTorch profiler traces to identify CPU overhead bottlenecks.

This script parses the .pt.trace.json.gz files generated by vLLM profiling
and identifies where CPU overhead is causing GPU idle time.

Usage:
    python analyze_traces.py --trace-dir ./traces
    python analyze_traces.py --trace-dir ./traces --output report.txt
    python analyze_traces.py --trace-dir ./traces --top-n 20
"""

import argparse
import gzip
import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Event:
    """Represents a profiling event."""

    name: str
    cat: str  # category
    pid: int  # process id
    tid: int  # thread id
    ts: float  # timestamp (microseconds)
    dur: float  # duration (microseconds)
    args: dict

    @property
    def dur_ms(self) -> float:
        """Duration in milliseconds."""
        return self.dur / 1000.0

    @property
    def is_cpu(self) -> bool:
        """Is this a CPU event?"""
        return self.cat not in ["cuda_runtime", "kernel", "gpu_memcpy", "gpu_memset"]

    @property
    def is_gpu(self) -> bool:
        """Is this a GPU kernel?"""
        return self.cat == "kernel"


def load_trace_file(filepath: Path) -> dict:
    """Load a trace file (supports .json and .json.gz)."""
    if filepath.suffix == ".gz":
        with gzip.open(filepath, "rt") as f:
            return json.load(f)
    else:
        with open(filepath) as f:
            return json.load(f)


def parse_events(trace_data: dict) -> list[Event]:
    """Parse trace events from the JSON data."""
    events = []

    # Handle different trace formats
    if "traceEvents" in trace_data:
        raw_events = trace_data["traceEvents"]
    elif isinstance(trace_data, list):
        raw_events = trace_data
    else:
        print(f"Warning: Unknown trace format, keys: {trace_data.keys()}")
        return events

    for event in raw_events:
        # Skip metadata events
        if event.get("ph") not in ["X", "B", "E"]:
            continue

        # For 'X' (complete) events
        if event.get("ph") == "X":
            try:
                events.append(
                    Event(
                        name=event.get("name", ""),
                        cat=event.get("cat", ""),
                        pid=event.get("pid", 0),
                        tid=event.get("tid", 0),
                        ts=event.get("ts", 0),
                        dur=event.get("dur", 0),
                        args=event.get("args", {}),
                    )
                )
            except Exception:
                # Skip malformed events
                continue

    return events


def analyze_cpu_overhead(events: list[Event], top_n: int = 10) -> dict:
    """
    Analyze CPU overhead by looking for CPU operations that might be
    blocking GPU execution.
    """
    # Group CPU events by name
    cpu_events_by_name = defaultdict(list)
    gpu_events = []

    for event in events:
        if event.is_gpu:
            gpu_events.append(event)
        elif event.is_cpu and event.dur > 0:
            cpu_events_by_name[event.name].append(event)

    # Calculate statistics for each CPU operation
    cpu_stats = {}
    for name, evts in cpu_events_by_name.items():
        total_time = sum(e.dur for e in evts)
        cpu_stats[name] = {
            "count": len(evts),
            "total_ms": total_time / 1000.0,
            "mean_ms": total_time / len(evts) / 1000.0,
            "max_ms": max(e.dur for e in evts) / 1000.0,
            "min_ms": min(e.dur for e in evts) / 1000.0,
        }

    # Sort by total time
    sorted_cpu = sorted(cpu_stats.items(), key=lambda x: x[1]["total_ms"], reverse=True)

    # GPU statistics
    gpu_stats = {
        "total_kernels": len(gpu_events),
        "total_gpu_time_ms": sum(e.dur for e in gpu_events) / 1000.0,
    }

    return {
        "cpu_operations": dict(sorted_cpu[:top_n]),
        "all_cpu_time_ms": sum(s["total_ms"] for s in cpu_stats.values()),
        "gpu_stats": gpu_stats,
        "num_cpu_operations": len(cpu_stats),
    }


def find_gpu_gaps(events: list[Event], threshold_ms: float = 1.0) -> list[dict]:
    """
    Find gaps in GPU execution where the GPU is idle.
    Returns list of gaps with what CPU operations were happening during the gap.
    """
    # Get all GPU events sorted by time
    gpu_events = sorted([e for e in events if e.is_gpu], key=lambda x: x.ts)

    gaps = []
    for i in range(len(gpu_events) - 1):
        curr_end = gpu_events[i].ts + gpu_events[i].dur
        next_start = gpu_events[i + 1].ts

        gap_duration = (next_start - curr_end) / 1000.0  # ms

        if gap_duration > threshold_ms:
            # Find CPU events during this gap
            cpu_during_gap = [
                e
                for e in events
                if e.is_cpu
                and e.ts >= curr_end
                and e.ts + e.dur <= next_start
                and e.dur > 0
            ]

            # Sort by duration
            cpu_during_gap.sort(key=lambda x: x.dur, reverse=True)

            gaps.append(
                {
                    "gap_start_us": curr_end,
                    "gap_end_us": next_start,
                    "gap_duration_ms": gap_duration,
                    "prev_kernel": gpu_events[i].name,
                    "next_kernel": gpu_events[i + 1].name,
                    "cpu_operations": [
                        {
                            "name": e.name,
                            "duration_ms": e.dur_ms,
                            "category": e.cat,
                        }
                        for e in cpu_during_gap[:5]  # Top 5 CPU ops during gap
                    ],
                }
            )

    # Sort gaps by duration
    gaps.sort(key=lambda x: x["gap_duration_ms"], reverse=True)
    return gaps


def search_for_pattern(events: list[Event], pattern: str) -> list[Event]:
    """Search for events matching a pattern (case-insensitive)."""
    pattern_lower = pattern.lower()
    return [e for e in events if pattern_lower in e.name.lower()]


def print_report(analysis: dict, gaps: list[dict], trace_file: str):
    """Print analysis report."""
    print("\n" + "=" * 80)
    print(f"TRACE ANALYSIS: {trace_file}")
    print("=" * 80)

    # GPU Stats
    print("\nGPU Statistics:")
    print(f"  Total GPU kernels:  {analysis['gpu_stats']['total_kernels']}")
    print(f"  Total GPU time:     {analysis['gpu_stats']['total_gpu_time_ms']:.2f} ms")

    # CPU Stats
    print("\nCPU Statistics:")
    print(f"  Total CPU operations: {analysis['num_cpu_operations']}")
    print(f"  Total CPU time:       {analysis['all_cpu_time_ms']:.2f} ms")

    # Top CPU operations
    print("\nTop CPU Operations (by total time):")
    print(
        f"{'Operation':<60} {'Count':>8} {'Total (ms)':>12} {'Mean (ms)':>12} {'Max (ms)':>12}"
    )
    print("-" * 80)

    for name, stats in analysis["cpu_operations"].items():
        # Truncate long names
        display_name = name[:57] + "..." if len(name) > 60 else name
        print(
            f"{display_name:<60} {stats['count']:>8} "
            f"{stats['total_ms']:>12.2f} {stats['mean_ms']:>12.4f} {stats['max_ms']:>12.4f}"
        )

    # GPU Gaps
    if gaps:
        print("\nTop GPU Idle Gaps (threshold > 1ms):")
        print(f"  Found {len(gaps)} gaps")
        print()

        for i, gap in enumerate(gaps[:10]):  # Show top 10 gaps
            print(f"Gap #{i + 1}: {gap['gap_duration_ms']:.2f} ms")
            print(f"  Between: {gap['prev_kernel']}")
            print(f"       and: {gap['next_kernel']}")

            if gap["cpu_operations"]:
                print("  CPU operations during gap:")
                for cpu_op in gap["cpu_operations"]:
                    print(
                        f"    - {cpu_op['name'][:60]}: {cpu_op['duration_ms']:.2f} ms"
                    )
            else:
                print("  No significant CPU operations captured during gap")
            print()
    else:
        print("\n✓ No significant GPU idle gaps found!")


def main():
    parser = argparse.ArgumentParser(
        description="Analyze PyTorch profiler traces for CPU overhead"
    )
    parser.add_argument(
        "--trace-dir",
        type=str,
        default="./traces",
        help="Directory containing trace files",
    )
    parser.add_argument(
        "--output", type=str, default=None, help="Output file for report"
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=15,
        help="Number of top CPU operations to show (default: 15)",
    )
    parser.add_argument(
        "--gap-threshold",
        type=float,
        default=1.0,
        help="Minimum GPU gap duration to report in ms (default: 1.0)",
    )
    parser.add_argument(
        "--search",
        type=str,
        default=None,
        help="Search for events matching pattern (e.g., 'shm_broadcast', 'dequeue')",
    )

    args = parser.parse_args()

    # Find all trace files
    trace_dir = Path(args.trace_dir)
    if not trace_dir.exists():
        print(f"Error: Trace directory not found: {trace_dir}")
        return

    trace_files = list(trace_dir.glob("*.pt.trace.json.gz")) + list(
        trace_dir.glob("*.pt.trace.json")
    )

    if not trace_files:
        print(f"No trace files found in {trace_dir}")
        print("Looking for: *.pt.trace.json.gz or *.pt.trace.json")
        return

    print(f"Found {len(trace_files)} trace file(s)")

    # Analyze each trace file
    for trace_file in trace_files:
        print(f"\nLoading: {trace_file.name}...")

        try:
            trace_data = load_trace_file(trace_file)
            events = parse_events(trace_data)

            if not events:
                print(f"  Warning: No events found in {trace_file.name}")
                continue

            print(f"  Parsed {len(events)} events")

            # Search mode
            if args.search:
                matching = search_for_pattern(events, args.search)
                print(f"\n{'=' * 80}")
                print(f"SEARCH RESULTS for '{args.search}' in {trace_file.name}")
                print(f"{'=' * 80}")
                print(f"Found {len(matching)} matching events\n")

                # Group by name
                by_name = defaultdict(list)
                for e in matching:
                    by_name[e.name].append(e)

                for name, evts in sorted(
                    by_name.items(),
                    key=lambda x: sum(e.dur for e in x[1]),
                    reverse=True,
                ):
                    total_ms = sum(e.dur for e in evts) / 1000.0
                    mean_ms = total_ms / len(evts)
                    print(f"{name}:")
                    print(
                        f"  Count: {len(evts)}, Total: {total_ms:.2f} ms, Mean: {mean_ms:.4f} ms"
                    )

                continue

            # Regular analysis
            analysis = analyze_cpu_overhead(events, top_n=args.top_n)
            gaps = find_gpu_gaps(events, threshold_ms=args.gap_threshold)

            print_report(analysis, gaps, trace_file.name)

            # Check for specific patterns
            print("\n" + "=" * 80)
            print("SPECIFIC PATTERN CHECKS:")
            print("=" * 80)

            # Check for shm_broadcast
            shm_events = search_for_pattern(events, "shm_broadcast")
            if shm_events:
                total_shm_ms = sum(e.dur for e in shm_events) / 1000.0
                print(f"\n✗ Found {len(shm_events)} shm_broadcast events")
                print(f"  Total time: {total_shm_ms:.2f} ms")
            else:
                print("\n✓ No shm_broadcast events found")

            # Check for dequeue
            dequeue_events = search_for_pattern(events, "dequeue")
            if dequeue_events:
                total_dequeue_ms = sum(e.dur for e in dequeue_events) / 1000.0
                print(f"\n✗ Found {len(dequeue_events)} dequeue events")
                print(f"  Total time: {total_dequeue_ms:.2f} ms")
            else:
                print("\n✓ No dequeue events found")

            # Check for _prepare_inputs
            prepare_events = search_for_pattern(events, "prepare_input")
            if prepare_events:
                total_prepare_ms = sum(e.dur for e in prepare_events) / 1000.0
                print(f"\n✗ Found {len(prepare_events)} prepare_input events")
                print(f"  Total time: {total_prepare_ms:.2f} ms")
                print(f"  Mean time: {total_prepare_ms / len(prepare_events):.4f} ms")
            else:
                print("\n✓ No prepare_input events found")

        except Exception as e:
            print(f"Error processing {trace_file.name}: {e}")
            import traceback

            traceback.print_exc()
            continue

    print("\n" + "=" * 80)
    print("Analysis complete!")
    print("=" * 80)


if __name__ == "__main__":
    main()
